project:
  type: website
  output-dir: docs

lang: pt-BR

execute: 
  freeze: auto

website:
  title: "Prof. Alcemy"
  site-url: "https://prof-alcemy.github.io"
  favicon: img/favicon.svg
  search: true

  navbar:
    # IMPORTANTE: Removi a linha 'background'. 
    # Agora a cor é controlada pelo 'site-custom.scss' (Verde no claro, Escuro no dark mode).
    
    # Adiciona o botão de alternar tema (Lua/Sol)
    tools:
      - icon: moon
        href: javascript:quarto.toggleDarkMode()
        
    left:
      - href: index.qmd
        text: Início
      - text: "🎓 Disciplinas"
        menu:
          # - href: disciplinas/etd/index.qmd
          #   text: "🌐 Educação em Tecnologias Digitais"
          # - href: disciplinas/ip/index.qmd
          #   text: "💻 Introdução à Programação"
          - href: disciplinas/ei/index.qmd
            text: "⚡Eletricidade Instrumental"
          # - href: disciplinas/omc/index.qmd
          #   text: "🛠️ Organização e Manutenção de Computadores"
      # - href: projetos.qmd
      #   text: "🔬 Projetos"
      # - href: publicacoes.qmd
      #   text: "📑 Publicações"
      - href: sobre.qmd
        text: "👨🏻‍🏫 Sobre Mim"
    right:
      - icon: github
        href: https://github.com/Prof-Alcemy
      - icon: mortarboard
        href: http://lattes.cnpq.br/7324129312150435
  
  page-footer:
    # Também removi o background fixo cinza. O tema cuidará disso.
    border: true              
    left: |
      © 2026 Prof. Alcemy Gabriel | IFRN
    right: |
      Este material está sob licença <a href="https://creativecommons.org/licenses/by-nc/4.0/deed.pt_BR" target="_blank">CC BY-NC 4.0</a>

format:
  html:
    # --- CONFIGURAÇÃO DO NOVO DESIGN SYSTEM ---
    # Usamos 'cosmo' como base limpa para o claro
    # Usamos 'darkly' como base para o escuro
    # E aplicamos suas regras personalizadas (site-custom.scss) em cima de ambos.
    theme:
      light: [cosmo, assets/scss/site-custom.scss]
      dark: [darkly, assets/scss/site-custom.scss]
    
    # Highlight de código inteligente (Claro para dia, Drácula para noite)
    highlight-style:
      light: github
      dark: dracula
      
    css: styles.css # Pode manter para ajustes pequenos que não sejam de cor
    toc: true
    toc-title: "Nesta página"
    code-copy: true
    smooth-scroll: true